name: zamzam
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutube: ^0.7.3
  youtube_player_flutter: ^6.1.0+4
  percent_indicator: "^2.1.1"
  flutter_money_formatter: ^0.8.3
  progress_indicators: "^0.1.4"
  flutter_verification_code_input:
      git:
        url: git://github.com/tinylife-io/flutter_verification_code_input.git
  flutter_spinkit: "^4.0.0" 
  country_pickers: ^1.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  carousel_slider: any
  flutter_swiper : ^1.1.6
  cupertino_icons: ^0.1.2
  firebase_auth:
  firebase_messaging: ^6.0.12
  shared_preferences: ^0.5.6+3
  http:
  font_awesome_flutter: ^8.4.0
  flutter_masked_text: ^0.7.0
  link: ^1.0.0
  url_launcher: ^5.4.2
  braintree_payment: ^1.2.3  #https://pub.dev/packages/braintree_payment
    
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/smartphone.png
  - assets/phone-charge.png
  - assets/iocl_tip.png
  - assets/add_money_passbook.png
  - assets/real.png
  - assets/logo.png
  - assets/powered_by.png
  - assets/book.png
  - assets/report.png
  - assets/donations.png
  - assets/ic_passbook_header.png
  - assets/amex.png
  - assets/visa.png
  - assets/discover.png
  - assets/mastercard.png




  - assets/zamzam.png
  - assets/help.png
  - assets/sadaka.png
  - assets/sanitation.png
  - assets/health.png
  - assets/empowerment.png
  - assets/marriage.png
  - assets/shelter.png
  - assets/education.png
  - assets/success-stories.png
  - assets/events.png
  - assets/calculator.png
  - assets/receipt.png
  - assets/profilebackground.png
  - assets/language.png
  - assets/child.png
  - assets/slider_1.png
  - assets/slider_2.png
  - assets/slider_3.png
  - assets/add_payment_method.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
